spring.datasource.url=jdbc:postgresql://localhost:5432/snaplink
spring.datasource.username=jobuser
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration