spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/snaplink}
spring.datasource.username=${DATABASE_USERNAME:jobuser}
spring.datasource.password=${DATABASE_PASSWORD:password123}
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration